name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Breaking'
    label: 'breaking'
  - title: 'Added'
    label: 
      - 'feature'
      - 'enhancement'
  - title: 'Fixed'
    label:
      - 'hotfix'    
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Changed'
    label: 'refactor'    
  - title: 'Maintenance'
    label:
      - 'maintenance'
      - 'chore'    
  - title: 'Documentation'
    label: 'docs'
  - title: 'Dependency Updates'
    label: 'dependencies'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'
      
      
autolabeler:
  - label: 'oneshop'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'   
    branch:
      - '/bugfix\/.+/'
    title:
      - '/bugfix/i'      
  - label: 'bug'   
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'      
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'      
  - label: 'chore'
    branch:
      - '/chore\/.+/'      
  - label: 'docs'
    branch:
      - '/docs\/.+/'            
    body:
      - '/JIRA-[0-9]{1,4}/'      

references:
  - master
  - v.+

exclude-labels:
  - 'skip-changelog'
