name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

  uses: Helmisek/conventional-changelog-generator@v1.0.6-release
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
