name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        id: "changelog-updater"
        with:
          # Pass extracted release date, release notes and version to the Action.
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.tag_name }}
          compare-url-target-revision: ${{ github.event.release.target_commitish }}

      - name: "release_compare_url"
        # https://github.com/org/repo/compare/v1.0.0...v1.1.0
        run: "echo ${{ steps.changelog-updater.outputs.release_compare_url }}"

      - name: "release_url_fragment"
        # #v100---2021-02-01
        run: "echo ${{ steps.changelog-updater.outputs.release_url_fragment }}"

      - name: "unreleased_compare_url"
        # https://github.com/org/repo/compare/v1.0.0...HEAD
        run: "echo ${{ steps.changelog-updater.outputs.unreleased_compare_url }}"

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
