name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          
          
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - uses: actions/checkout@master
      - name: Master main -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ github.token }}