name: release

on:
  push:
    branches:
    - main
  pull_request:
    types: [closed]
    branches:
    - main


jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure committer
        run: |
          git config --local user.email "carlosvalentin.diaz@decathlon.com"
          git config --local user.name "pythonicv"
      - name: Standard Version
        uses: qzb/standard-version-action@v1.0.1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
